apiVersion: v1
kind: ConfigMap
metadata: { name: product-config, namespace: ecommerce }
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/microservices_pro
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "2"
  SPRING_DATA_REDIS_HOST: host.docker.internal
  EUREKA_CLIENT_ENABLED: "false"
